name: Python application
on:
  workflow_dispatch:
  push:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: dingding
    steps:
    - name: checkout actions
      uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run py script
      env:
        DINGDING_TOKEN: ${{ secrets.token }}
        DINGDING_SECRET: ${{ secrets.secret }}
      run: |
        python main.py "$DINGDING_TOKEN" "$DINGDING_SECRET"
