name: main
on:
  workflow_dispatch:
  push:
    branches: [ "master", "main" ]
  schedule:
    - cron: '0 */8 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: dingding
    steps:
      - name: checkout actions
        uses: actions/checkout@v4

      - name: Set up Python 3.7
        uses: actions/setup-python@v5
        with:
          python-version: 3.7
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run py script
        env:
          DINGDING_TOKEN: ${{ secrets.token }}
          DINGDING_SECRET: ${{ secrets.secret }}
        run: |
          python main.py "$DINGDING_TOKEN" "$DINGDING_SECRET"

      - name: commit
        run: |
          git config --global user.email mrwq@qq.com
          git config --global user.name mrwq
          git add wiki.db
          git commit -m "update"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
